version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"    
  gateway:
    build: ./gateway
    ports:
    - 8080:8080
    depends_on: 
    - account-service
    - redis
  account-service:
    build: ./account-service-mvc
    ports:
    - 8091:8091
