spring:
  application:
    name: account-service-mvc 
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true  
        
server:
  port : 8091
  
management:
  endpoints:
    web.exposure.include: '*'
    
accesslog:
  enabled: true
  



